# Estágio de compilação
FROM golang:1.20-alpine AS build

RUN apk add --no-cache git

WORKDIR /app
COPY main.go .
COPY go.mod .

RUN go build -o app

# Estágio de produção
FROM scratch
WORKDIR /app
COPY --from=build /app/app .
EXPOSE 5000
CMD ["./app"]
